language: java

jdk:
- oraclejdk8
- openjdk8

cache:
   repository:
   - '$HOME/.m2/repository'

before_script:
- echo $HOME
- echo $JAVA_OPTS
- echo $MAVEN_OPTS

script: pwd && ls -al && mvn clean package

deploy:
  provider: heroku
  api_key:
      secure: $HEROKU_AUTH_TOKEN
  app : jsf-travis-ci-heroku
  on:
     branch: master
